# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - duman_left_controller
    - duman_right_controller

  duman_left_controller:
    type: FollowJointTrajectory
    joints:
      - left_hip
      - left_shoulder
      - left_elbow
      - left_wrist1
      - left_wrist2
      - left_wrist3
    action_ns: follow_joint_trajectory
    default: true
  duman_right_controller:
    type: FollowJointTrajectory
    joints:
      - right_hip
      - right_shoulder
      - right_elbow
      - right_wrist1
      - right_wrist2
      - right_wrist3
    action_ns: follow_joint_trajectory
    default: true