# Goal
bool arm # 0-right 1-left
float32 hip
float32 shoulder
float32 elbow
float32 wrist1
float32 wrist2
float32 wrist3
---
# Result
bool success # true if task completed
string message
---
# Feedback
bool plan_done # if planning is done
bool execution # if execution started
